### ISSUE TITLE
The minskins 02-11-20

### ISSUE THREAD

**Issue by carlosveigadev** [Bismarck-GM/restaurant-js#2]
Really good job buddy!
Keep up the great work!

![gif](https://media.giphy.com/media/yJFeycRK2DB4c/giphy.gif)

:star: :star: :star: :star: :star: :star: :star: :star: :star: :star: :star: :star: :star: :star: :star: :star: :star: :star: :star: :star: :star: :star: :star: :star: :star:

**Comment by Bismarck-GM** [comment]
Lol. Thanks for the reminder to close this @carlosveigadev !!!
